### PR TITLE
Update operator availability as unavailable upon going offline

### PR DESCRIPTION
**Pull request by southp**
## Summary
The action `SET_USER_OFFLINE` should not only set `online` as false but also set `status` as `unavailable`.

## Test Plan
Run `npm test`

### CODE REVIEW

**Comment by jordwest** [comment]
LGTM. My only concern is what happens when we deploy or an operator gets disconnected temporarily - I assume their status would automatically be set to unavailable. Do you know how long a delay there is before an operator is considered 'offline'?

**Review by unDemian — APPROVED** [review]
Looks good to me.

**Comment by southp** [comment]
@jordwest 
> My only concern is what happens when we deploy or an operator gets disconnected temporarily - I assume their status would automatically be set to unavailable. Do you know how long a delay there is before an operator is considered 'offline'?

To be honest, I don't have a solid idea about this 😅
In my local dev environment, the case I've tested is simply to close the operator tab and see how long it takes to see an offline event. In my case, it was less than a second, so I imagine it would be a few seconds on production. The other ways of disconnecting could be a temporary connection outage from the operator end or the server end, but I don't know how to test that locally.

Do you have any tips on how to do that?

**Comment by jordwest** [comment]
Hmm, I haven't been able to find a simple way to make this work either, other than closing the tab. It should be easy enough to test on staging (disconnect the internet), so let's merge as is and we can work out any kinks there as needed. I don't think it's really a blocker either way, possibly just an inconvenience when it happens (which should be rarely)

**Pull request merged**
