### PR TITLE
Move tests to subfolders

### PR DESCRIPTION
**Pull request by unDemian**
Part of devex moving tests to subfolders
More details about testing this in the ticket: https://github.com/Automattic/happychat/issues/396

**Implementation details**
- Added a `mocha` test runner
- Moved unit tests to subfolders
- Added empty test file for all existing files

### CODE REVIEW

**Comment by dllh** [comment]
Didn't test it, but this seems fine to me at a glance. One thing -- does this play nicely with our move of happychat-service into the happychat repo?

**Comment by unDemian** [comment]
It might be the case the this will need a bit of rework for paths after we merge the service. That is why we should finish that as soon as possible so we don't pile too many PRs on the service.

**Comment by southp** [comment]
Thanks for putting up with the challenge. I believe this is one of our most tedious work 🙇🏻

I believe `has-flag` and `nodemon` are missing from the dependency list, and thus causes `npm run test:coverage` and `npm run test:watch` to fail. e.g.

```
(update/move-tests)->$ npm run test:coverage

> happychat-service@0.18.0 test:coverage /Users/southp/a8c/happychat-service
> NODE_PATH=./src babel-node ./test/runner.js --coverage

Cannot find module 'has-flag'
Error: Cannot find module 'has-flag'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/southp/a8c/happychat-service/node_modules/istanbul/node_modules/supports-color/index.js:2:15)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/southp/a8c/happychat-service/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```
and
```
(update/move-tests)->$ npm run test:watch

> happychat-service@0.18.0 test:watch /Users/southp/a8c/happychat-service
> nodemon -e js,jsx --exec npm run test:min

sh: nodemon: command not found

npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/southp/.nvm/versions/node/v7.5.0/bin/node" "/Users/southp/.nvm/versions/node/v7.5.0/bin/npm" "run" "test:watch"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! happychat-service@0.18.0 test:watch: `nodemon -e js,jsx --exec npm run test:min`
npm ERR! spawn ENOENT
```

Also, with this change, the root `/test` directory now looks like encapsulating every common code uses across tests. Is there a way to add it to the module resolution path when running a test so that we can eliminate thins like `import { *** } from '../../../../test/***'`?

**Comment by unDemian** [comment]
Thanks for taking the time to test this. I agree that relative paths are really ugly, node only allows one node_path dir, so I used the root dir `.` as `NODE_PATH` for tests which means in test files we should also add `src` to imports from `src` folder. This way all imports look good.

Those errors are pretty weird, `has-flags` is not a direct dependency and `nodemon` is part of the package.json. Can you please try to `rm -rf node_modules && npm cache clean && npm install`. It works ok on circle because the coverage artifacts are there https://489-52473446-gh.circle-artifacts.com/0/home/ubuntu/happychat-service/coverage/index.html

Ready for re-review.

**Comment by beaucollins** [comment]
You can supply multiple `NODE_PATH` directories. They need to be separated by `:`.

**Comment by unDemian** [comment]
This was moved to https://github.com/Automattic/happychat/pull/455

**Pull request closed without merging**
