### PR TITLE
Operator transfer

### PR DESCRIPTION
**Pull request by beaucollins**
Allow operators to transfer assigned chats.

### CODE REVIEW

**Comment by beaucollins** [comment]
The client can issue a `chat.transfer` with the chat_id and the operator_id to transfer the chat to.

``` js
client.emit( 'chat.transfer', CHAT_ID, OPERATOR_ID )
```

The service will assign the chat to the new operator and open the chat on their client.

**Comment by mjangda** [comment]
Do we need to do anything in the HUD if the transfer fails? Or just go with a best case scenario?

**Comment by beaucollins** [comment]
At this point if the transfer fails (client timeout or unavailability) the customer is routed back to the queue to be reassigned to the next available operator.

At this point we don't have much in the way of log messages (e.g. operator assigned, operator joined) but this could be something that gets logged in the operator chat history.

**Comment by mjangda** [comment]
Will the standard `chat.close` (transferer) and `chat.open` (transferee) events fire? Or is there a new `transfer` event?

Also, should we just handle the log messages in the HUD for now?

**Comment by beaucollins** [comment]
At this point the user initiating the transfer does not receive any confirmation that the chat was transferred.

We could add a customer channel wide message that tells any listening operators that the chat assignment has changed.

**Comment by beaucollins** [comment]
As for `chat.close` and `chat.open` the transferee would receive a `chat.close` event only if they or another operator chose to close the chat. So after transferring the chat they could still stay in the chat and participate if they wanted to.

**Comment by mjangda** [comment]
Okay, so here's the use case I've been working against:

Marcus gets a chat from user. Realizes that Andrea is probably better person to chat with the user. Marcus transfers the chat to Andrea. Here's what I've been thinking should happen:

1) Marcus: chat moves to `ended` chats list. A `type=event` message with text is added to the conversation with text `Chat transferred to Andrea`. 
2) Andrea: receives the chat and is added to her `open` chats list in HUD. The chat history (from Marcus' conversation with the user) is included and the last message is `type=event` with text `Chat transferred by Marcus`. Andrea can now chat with the user.
3) User: continues on obliviously chatting to Agent W as if nothing changed.

An alternative I can see to `1)` is that Marcus stays in the chat but can chose to `/leave` at any point. (`/add`, `/join`, `/leave` might be interesting commands to add for operators at some point anyway) although, HEs may just want this to happen automatically (i.e. "fire and forget").

/cc @andreabadgley for her input

**Comment by andreabadgley** [comment]
These steps look great to me, @mjangda. 

> HEs may just want this to happen automatically (i.e. "fire and forget").

This is mostly true ;-) `/transfer` = get this out of my chats! However, confirmation that the chat has successfully transferred to the other HE is important so that the transferring HE knows the user is taken care of. Perhaps the message in `1)` could be `Chat successfully transferred to Andrea` for clarity.

**Comment by beaucollins** [comment]
As for the `chat.close` event. Right now it means that the customer's issue has been resolved and is a chat status shared across all operators.

There's nothing at this time that indicates the chat is closed for a particular operator.

Operators can join and leave chats whenever they wish so I can have the operator who initiated the transfer also leave the chat.

The service does have a master list of all available chats, so I could possibly tack the state for particular operators as a history of sorts.

**Pull request merged**
